server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: test1234
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///D:/native-file-repo
        git:
#          uri: file://D:/git-local-repo
            uri: https://github.com/TomyRavn/spring-cloud-config
            default-label: master
#  profiles:
#    active: native
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
